# Generated by Django 3.2.4 on 2023-04-04 05:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elshopapp', '0002_alter_filter_price_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_price',
            name='price',
            field=models.CharField(choices=[('20000 TO 50000', '20000 TO 50000'), ('1000 TO 5000', '1000 TO 5000'), ('10000 TO 20000', '10000 TO 20000'), ('500', '500 TO 1000'), ('5000 TO 10000', '5000 TO 10000'), ('50000 TO 100000', '50000 TO 100000')], max_length=60),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('image', models.ImageField(upload_to='Product_images/img')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('condition', models.CharField(choices=[('Old', 'Old'), ('New', 'New')], max_length=100)),
                ('information', models.TextField()),
                ('description', models.TextField()),
                ('stock', models.CharField(choices=[('OUT OF STOCK', 'OUT OF STOCK'), ('IN STOCK', 'IN STOCK')], max_length=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Publish', 'Publish')], max_length=100)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elshopapp.brand')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elshopapp.categories')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elshopapp.color')),
                ('filter_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elshopapp.filter_price')),
            ],
        ),
    ]
