# Generated by Django 3.2.4 on 2023-04-08 18:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elshopapp', '0006_auto_20230407_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_price',
            name='price',
            field=models.CharField(choices=[('5000 TO 10000', '5000 TO 10000'), ('10000 TO 20000', '10000 TO 20000'), ('500', '500 TO 1000'), ('1000 TO 5000', '1000 TO 5000'), ('20000 TO 50000', '20000 TO 50000'), ('50000 TO 100000', '50000 TO 100000')], max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('Old', 'Old'), ('New', 'New')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='information',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Publish', 'Publish'), ('Draft', 'Draft')], max_length=100),
        ),
    ]
