# Generated by Django 4.2 on 2023-04-20 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elshopapp', '0034_alter_filter_price_price_alter_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_price',
            name='price',
            field=models.CharField(choices=[('20000 TO 50000', '20000 TO 50000'), ('1000 TO 5000', '1000 TO 5000'), ('10000 TO 20000', '10000 TO 20000'), ('5000 TO 10000', '5000 TO 10000'), ('500', '500 TO 1000'), ('50000 TO 100000', '50000 TO 100000')], max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('Old', 'Old'), ('New', 'New')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Publish', 'Publish'), ('Draft', 'Draft')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(choices=[('OUT OF STOCK', 'OUT OF STOCK'), ('IN STOCK', 'IN STOCK')], max_length=100),
        ),
        migrations.CreateModel(
            name='AddressMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('India', 'India'), ('Australia', 'Australia'), ('Bangladesh', 'Bangladesh'), ('Barbados', 'Barbados'), ('SriLanka', 'SriLanka'), ('Bhutan', 'Bhutan'), ('Pakistan', 'Pakistan')], max_length=20)),
                ('city', models.CharField(choices=[('Jamshedpur', 'JamshedPur'), ('MuzaffarPur', 'MuzaffarPur'), ('Shimla', 'Shimla'), ('Cuttack', 'Cuttack'), ('Patna', 'Patna'), ('Kolkata', 'Kolkata'), ('Bhubaneswar', 'Bhubbanewsar'), ('Ahemdabad', 'Ahemdabad')], max_length=20)),
                ('state', models.CharField(choices=[('Mumbai', 'Mumbai'), ('Bihar', 'Bihar'), ('W.Bengal', 'W.Bengal'), ('Jharkhand', 'Jharkhand'), ('Gujrat', 'Gujrat'), ('Odisha', 'Odisha'), ('Himachal', 'Himachal')], max_length=20)),
                ('area', models.TextField()),
                ('phone', models.IntegerField()),
                ('zipcode', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
