# Generated by Django 4.2 on 2023-04-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elshopapp', '0037_alter_addressmod_city_alter_addressmod_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmod',
            name='city',
            field=models.CharField(choices=[('Kolkata', 'Kolkata'), ('Cuttack', 'Cuttack'), ('MuzaffarPur', 'MuzaffarPur'), ('Bhubaneswar', 'Bhubbanewsar'), ('Ahemdabad', 'Ahemdabad'), ('Patna', 'Patna'), ('Shimla', 'Shimla'), ('Jamshedpur', 'JamshedPur')], max_length=20),
        ),
        migrations.AlterField(
            model_name='addressmod',
            name='country',
            field=models.CharField(choices=[('Pakistan', 'Pakistan'), ('SriLanka', 'SriLanka'), ('Australia', 'Australia'), ('Bhutan', 'Bhutan'), ('Barbados', 'Barbados'), ('India', 'India'), ('Bangladesh', 'Bangladesh')], max_length=20),
        ),
        migrations.AlterField(
            model_name='addressmod',
            name='state',
            field=models.CharField(choices=[('W.Bengal', 'W.Bengal'), ('Mumbai', 'Mumbai'), ('Gujrat', 'Gujrat'), ('Jharkhand', 'Jharkhand'), ('Himachal', 'Himachal'), ('Odisha', 'Odisha'), ('Bihar', 'Bihar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='filter_price',
            name='price',
            field=models.CharField(choices=[('500', '500 TO 1000'), ('20000 TO 50000', '20000 TO 50000'), ('10000 TO 20000', '10000 TO 20000'), ('5000 TO 10000', '5000 TO 10000'), ('1000 TO 5000', '1000 TO 5000'), ('50000 TO 100000', '50000 TO 100000')], max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('Old', 'Old'), ('New', 'New')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Publish', 'Publish')], max_length=100),
        ),
    ]
